export const theme = {
  colors: {
    primary: '#2E5BFF',
    primaryDark: '#1a3fb0',
    secondary: '#00C48C',
    danger: '#FF3B30',
    warning: '#FF9500',
    success: '#34C759',
    background: '#F5F7FA',
    surface: '#FFFFFF',
    text: '#1A1A2E',
    textLight: '#666666',
    border: '#E5E9F0',
    placeholder: '#999999',
  },
  typography: {
    fontFamily: {
      regular: 'System',
      bold: 'System',
    },
    fontSize: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
      xxxl: 32,
    },
    fontWeight: {
      normal: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 999,
  },
};